---
title: "State Examples"
author: "Craig Savage"
date: "25/05/2021"
output: 
    html_document:
      code_folding: hide
      highlight: espresso
params: 
    jobsData: NULL
---

# Overview {.tabset}

Below is an example of a `highcharter` graph[^1].

[^1]: Use of [Highcharts](https://www.highcharts.com/) for commercial or government purposes requires a [license](https://www.highcharts.com/download/).

```{r exPlot, echo=TRUE, warning=FALSE, message=FALSE, results='asis'}
statePlotData <- params$jobsData %>%
  group_by( STE_NAME16, Date ) %>%
  summarise( meanIndex=mean( Index ), .groups='drop' )

hcState <- hchart( statePlotData
                   , type='line' 
                   , hcaes( x=Date, y=meanIndex, group=STE_NAME16 ) ) %>%
  hc_title(text='State-level time series of wage indices' ) %>%
  hc_tooltip( table=TRUE, valueDecimals=2 )

hcState
```

Use of tabs is possible in HTML documents:

```{r echo=TRUE, warning=FALSE, message=FALSE, comment='', results='asis'}
makeStateSlide <- function( stateData
                            , templateRMD='stateChild.Rmd' ){
  stateEnv <- new.env()
  assign( 'stateData', stateData, env=stateEnv )
  stateSlide <- knit_child( templateRMD
                            , envir=stateEnv
                            , options=list( output.dir='./' )
                            , quiet=TRUE )
  return( stateSlide )
}

jobsSA4 <- params$jobsData
subList <- split( jobsSA4, list( jobsSA4$bigCity, jobsSA4$STE_NAME16 ), drop=TRUE )

stateRMD <- map( subList, ~makeStateSlide( stateData=. ) )

cat( unlist( stateRMD ), sep='\n' )

```




